from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Sequence

from .discovery import (
    DiscoveryError,
    discover_from_config,
    discover_from_server_url,
    discover_from_stdio_command,
    load_tools_file,
)
from .lint import lint_sources
from .models import LintConfig, SourceResult
from .reporting import (
    exit_code_for_report,
    optimize_from_report,
    report_to_json,
    report_to_markdown,
    write_json_report,
    write_markdown_report,
)


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        if args.command == "lint":
            return _run_lint(args)
        if args.command == "optimize":
            return _run_optimize(args)
        parser.print_help(sys.stderr)
        return 2
    except DiscoveryError as exc:
        print(f"discovery error: {exc}", file=sys.stderr)
        return 2
    except OSError as exc:
        print(f"io error: {exc}", file=sys.stderr)
        return 2
    except KeyboardInterrupt:
        print("interrupted", file=sys.stderr)
        return 130


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="mcp-tool-card-linter",
        description="Lint MCP tool metadata for schema quality, description clarity, side effects, and tool-poisoning risks.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    lint_parser = subparsers.add_parser("lint", help="Discover and lint MCP tools")
    source = lint_parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--tools-file", help="JSON file containing tools or result.tools")
    source.add_argument("--config", help="MCP config file containing mcpServers")
    source.add_argument("--stdio", help="Command line for a stdio MCP server")
    source.add_argument("--server-url", help="Streamable HTTP MCP endpoint URL")
    lint_parser.add_argument("--server", help="Server name for config filtering or report labeling")
    lint_parser.add_argument("--json-report", help="Write machine-readable JSON report")
    lint_parser.add_argument("--markdown-report", help="Write human-readable Markdown report")
    lint_parser.add_argument(
        "--fail-on",
        choices=["critical", "error", "warning", "info", "never"],
        default="error",
        help="Exit with code 1 when findings at this severity or higher are present; source failures return code 2.",
    )
    lint_parser.add_argument("--timeout", type=float, default=10.0, help="MCP request timeout in seconds")
    lint_parser.add_argument("--max-tools", type=_positive_int, default=1000, help="Maximum tools to lint per source")
    lint_parser.add_argument("--concurrency", type=_positive_int, default=4, help="Concurrent servers for config discovery")
    lint_parser.add_argument("--max-schema-depth", type=_positive_int, default=8)
    lint_parser.add_argument("--max-schema-properties", type=_positive_int, default=2000)
    lint_parser.add_argument("--max-card-chars", type=_positive_int, default=2800)
    lint_parser.add_argument("--max-description-chars", type=_positive_int, default=1200)
    lint_parser.add_argument(
        "--format",
        choices=["markdown", "json", "none"],
        default="markdown",
        help="Stdout format. Use none when only report files are desired.",
    )

    optimize_parser = subparsers.add_parser(
        "optimize",
        help="Generate allowlist/approval/block decisions from a JSON lint report",
    )
    optimize_parser.add_argument("--input-report", required=True, help="JSON report generated by lint")
    optimize_parser.add_argument("--output", help="Write optimization JSON to this path")
    return parser


def _run_lint(args: argparse.Namespace) -> int:
    sources = _discover_sources(args)
    config = LintConfig(
        max_tools=args.max_tools,
        max_schema_depth=args.max_schema_depth,
        max_schema_properties=args.max_schema_properties,
        max_card_chars=args.max_card_chars,
        max_description_chars=args.max_description_chars,
    )
    report = lint_sources(sources, config)
    if args.json_report:
        write_json_report(report, args.json_report)
    if args.markdown_report:
        write_markdown_report(report, args.markdown_report)
    if args.format == "markdown":
        print(report_to_markdown(report), end="")
    elif args.format == "json":
        print(report_to_json(report))
    return exit_code_for_report(report, args.fail_on)


def _discover_sources(args: argparse.Namespace) -> list[SourceResult]:
    if args.tools_file:
        server_name = args.server or "static"
        return [load_tools_file(args.tools_file, server_name=server_name)]
    if args.config:
        return discover_from_config(
            args.config,
            server_filter=args.server,
            timeout=args.timeout,
            max_tools=args.max_tools,
            concurrency=args.concurrency,
        )
    if args.stdio:
        return [
            discover_from_stdio_command(
                args.stdio,
                server_name=args.server or "stdio",
                timeout=args.timeout,
                max_tools=args.max_tools,
            )
        ]
    if args.server_url:
        return [
            discover_from_server_url(
                args.server_url,
                server_name=args.server or "http",
                timeout=args.timeout,
                max_tools=args.max_tools,
            )
        ]
    raise DiscoveryError("No source selected")


def _run_optimize(args: argparse.Namespace) -> int:
    payload = json.loads(Path(args.input_report).expanduser().read_text(encoding="utf-8"))
    optimized = optimize_from_report(payload)
    text = json.dumps(optimized, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    if args.output:
        resolved = Path(args.output).expanduser().resolve()
        resolved.parent.mkdir(parents=True, exist_ok=True)
        resolved.write_text(text, encoding="utf-8")
    else:
        print(text, end="")
    return 0


def _positive_int(value: str) -> int:
    number = int(value)
    if number <= 0:
        raise argparse.ArgumentTypeError("must be positive")
    return number

